[build-system]
requires = [
  "setuptools >= 43.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.bandit]
exclude_dirs = ["/tests/", "/venv/"]

[tool.pylint.messages_control]
disable = """
C0103
"""
